### ISSUE TITLE
Consumer recieves msg with packetId every 100

### ISSUE THREAD

**Issue by xiangwangcheng** [hivemq/hivemq-community-edition#182]
## Expected behavior
consumer recieves msg with packetId consecutively increase
## Actual behavior
consumer recieves msg with packetId inceasing by 100. As below:
![image](https://user-images.githubusercontent.com/8049014/86230572-d7195580-bbc3-11ea-835a-2f693d40c9d9.png)

## Details
- Affected HiveMQ CE version(s): 
- Used JVM version:

**Comment by fraschbi** [comment]
Hi @xiangwangcheng,

Thank you for reaching out. I was wondering what made you think that the expected behaviour is that each packed identifier is incremented by one. 
The [MQTT Specification](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc358219870) says: 

> Each time a Client sends a new SUBSCRIBE, UNSUBSCRIBE,or PUBLISH (where QoS > 0) MQTT Control Packet it MUST assign it a non-zero Packet Identifier that is currently unused

The behaviour you are observing is actually expected.

Best regards,
Florian

**Comment by xiangwangcheng** [comment]
@fraschbi  Maybe some other mqtt brokers make me think that way. 
BTW, what is the benefit of making packet id incrementing by 100 instead of 1.

**Comment by SgtSilvio** [comment]
Hi @xiangwangcheng 
HiveMQ does not increment the packet identifier by 100, an order of packet identifiers does simply not exist.
This just happens in your scenario due to internal implementation details, but the packet identifiers could be chosen completely random.
