### ISSUE TITLE
Parameter not used for initialization

### ISSUE THREAD

**Issue by sakib-malek** [hivemq/hivemq-community-edition#200]
## Expected behavior
File:  hivemq-community-edition/src/main/java/com/hivemq/mqtt/topic/SubscriberWithIdentifiers.java 

Function:
`public SubscriberWithIdentifiers(final @NotNull String subscriber, final int qos, final byte flags, final @Nullable String sharedName, final @NotNull ImmutableList<Integer> subscriptionIdentifier, final @Nullable String topicFilter)`

Parameter `subscriptionIdentifier` is not used for setting the `subscriptionIdentifier`

## Actual behavior
Creates a new empty list for `subscriptionIdentifier`

## Details
File link:
https://github.com/hivemq/hivemq-community-edition/blob/master/src/main/java/com/hivemq/mqtt/topic/SubscriberWithIdentifiers.java#L52

The bug is still present in **master** branch.

- Affected HiveMQ CE version(s): 2020.4
- Used JVM version:

**Comment by DC2-DanielKrueger** [comment]
Actually this is no bug as the constructor is only used for unit tests and not in productive code. However one can see this as a technical debt (i personally dont like to make constructors for unit test only). As this is not a really bug, i close this issue. I closed the PR, because it had test failures and was stale for 6 months.
