### ISSUE TITLE
Adding Back-off Algorithm

### ISSUE THREAD

**Issue by be320** [hivemq/hivemq-community-edition#238]
I want to know where I can add back-off algorithm that makes the broker handles its clients.

**Comment by SgtSilvio** [comment]
Hi @be320 
It is not clear what your issue is about.
Are you referring to reconnecting clients with an exponential backoff algorithm? This can not be configured on the broker side, but instead on the client side.

I will close this issue now. Please feel free to comment or open a new issue with more details if I misunderstood something.
