### ISSUE TITLE
SpringBoot + HiveMQ embedded = Not able to create folder ... HiveMQ will behave unexpectedly!

### ISSUE THREAD

**Issue by FibreFoX** [hivemq/hivemq-community-edition#299]
## Expected behavior

HiveMQ embedded in spring boot project being able to run without error message being shown.

## Actual behavior

When starting HiveMQ embedded results having this error message
```
2021-09-07 13:37:49,600 WARN  - Not able to create folder file:\C:\tmp\issuemqttembeddedspringboot\target\issuemqttembeddedspringboot-1.0.0-SNAPSHOT.jar!\BOOT-INF\lib\hivemq-community-edition-embedded-2021.2.jar!\data, HiveMQ will behave unexpectedly!
```

Is this due to spring-boot having some magic about INCLUDED jar dependencies? Am I doing something totally wrong?

Actually tried to check if this is `setFolders` inside `SystemInformationImpl.java` gets called multiple twice ... or being set wrongly, but did not found something. https://github.com/hivemq/hivemq-community-edition/blob/559c6730b83fc5e6f296d8fb8c409c876e218a9b/src/main/java/com/hivemq/configuration/info/SystemInformationImpl.java#L117

### Steps

Create instance of embedded HiveMQ server after `SpringApplication.run`.

### Reproducer code

I created a project (including all details) to have this reproduceable:
https://github.com/FibreFoX/issuemqttembeddedspringboot

## Details
- Affected HiveMQ CE version(s): 2021.2
- Used JVM version: openjdk version "11.0.12"

**Comment by HiveMQSupport** [comment]
Tune in to our upcoming webinars –– What's New in HiveMQ 4.7 & Testing MQTT in the Cloud Using MQTT.fx®

Dear hivemq/hivemq-community-edition,

It’s our pleasure to invite you to two of our upcoming webinars this month:

- What's New in HiveMQ: Inside the Upcoming HiveMQ 4.7 Release (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVqq5p1dzhGxW5r2R8b4QC9-yW861hN74xc2j1N7Hm8wG5mVy7V3Zsc37CgFVwVGc9Cs3Mp8rFN7xqW2yQt4YjW1P7ySD4xxB9PW12cVm76ZZgn1W2hJkyp1fJcrHW54mtYD1yXtLsW3jYSY55rkmW1W4YPS8f5gSLsQMkw7PBGKBQyW1GVgKL1tW_pwW6f8t1t7ysLd2W2xTG8x3rVdhcW2YmBvH2jzhPCVBxJx132z9WHW2sCSjn5qqsDqW2KkNKg8XqvnMW3b4SCd7GZ8-SW4PcD3W1YP6_1N5-8Zh4yGz1WN2QW88ZNJ3yVW2qsyzW3GSs85W35lLrh4j45BpW6L50nt2X_X11W7fFWW37kPNCPV3ZVW28Kl5x6W7j0VF-5Vt-NCW1pjmhC7Gzh__W8dscPY5FHQQ_W6L6H0z94CQCcN8B7GsT39yQZN4psv1nSHqDrVpGF-167Z4qXN4gFd9LKljlgVFlSk15DrnrJ3lHl1 )
- MQTT.fx® on HiveMQ Cloud: Testing MQTT in the Cloud is Now Easier Than Ever (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVqq5p1dzhGxW5r2R8b4QC9-yW861hN74xc2j1N7Hm8wG5mVy7V3Zsc37CgCYmW6_BxjS6MTlFhN1Y2dxDFMn4nW6twgwf4v8r00W4DY-sM75TbTWW4m7Wz_7n79ThW1pFmMN38jvdHN3clFsj769CqW2Hx4mL58GcJmW8Xd7jC1-x3QnN1tys-kBcNyjW7G_XNR2S8jzxW6R9-284rdH4jN7Tp316XJXSgW33Zdll8BfF9XW37dPZf6Ys9WwN8gbC8ZbhqPGVNypnK6wLl-ZW8C_k9816srclW8L3tM394tr1pW1XRDZh1XjP4lW2kPgfZ1RdhvBW7W6K4n7D1L4GW678xTX8Dn7dWW5LpJMy5dHhVvW7jhDCL1gD6kBW1j6zPm8ZNQmXW2R1hj56gQTFrW8fkcqb51MnWLW3Hg8N56H0R-fW2Yxxmy8F95V_W3hRm3D2444ZdN6crNqGG5QLnVMbHB71x1QySW17F2nn8LBFh23c1H1 )

Why You Should Attend:

>> What's New in HiveMQ: Inside the Upcoming HiveMQ 4.7 Release

In the webinar, Dominik Obermaier, CTO and co-founder of HiveMQ, and Georg Held, Engineering Manager at HiveMQ, will showcase the new features of HiveMQ 4.7 and discuss how customers can benefit from upgrading to the new release.

Date: Wednesday, September 15. 2021

Time: 5 pm CEST / 11 am ET / 8 am PT

Register Now
(https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVqq5p1dzhGxW5r2R8b4QC9-yW861hN74xc2j1N7Hm8wG5mVy7V3Zsc37CgH5YW7RTp8z1hcgWgVplKQz34JsQpW6PjPM18x73MhM13LMSJnlchW1j955-5c1GrqW3LScZY3THNGkW2025YP1YlCDsW1fCg954dDl9NW520DxV8sSq8JV9YzYd2V5gWhW7p5gDS77_8gNVk2rdX62sfW_W52-ykr1pkrlZW6xVxq33bqyg2W1F-TKJ57H1stW8WHVrV7869rgW3Tz8Xq8yMgksW2DH5f15mTD8lW5bGMG868n5DYW5P_SVP4yTpq8W7xTmcl5Rl4qmN2gKC_b36rQqW8mrtNy54d97QW4V31yw8315zkW4QybL94fB4FKN1J9RGpxLJCdW6-7nDQ2Mzp8fW5hJc822hF-vgN4SJSR7xgTj_W826GTz7Gr0KxW6b5m163X_CGNW4sVn_G1H6yYFW7bs_pb8HvyT3W4XdV0p39qBjL3lG61 )

>> MQTT.fx® on HiveMQ Cloud: Testing MQTT in the Cloud is Now Easier Than Ever

In the webinar, Magi Erber, Product Manager at HiveMQ, will show you how simple it is to set up HiveMQ Cloud, on AWS or Azure, and increase the number of MQTT connections according to the demands of your IoT use case. Further in the session, Jens Deters, Founder and CEO of Softblade, and Nikolas Blättermann, COO of Softblade, together will show how easy it is to test, simulate and debug your MQTT client connections as you scale your IoT project with the new MQTT.fx® for HiveMQ Cloud edition.

Date: Wednesday, September 29. 2021

Time: 5 pm CEST / 11 am ET / 8 am PT

Register Now
(https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVqq5p1dzhGxW5r2R8b4QC9-yW861hN74xc2j1N7Hm8wG5mVy7V3Zsc37CgNrhW2BNr5-4XHwfKW5dGKVr4H3MppW3MPvlb67sm6bW3vL8jX8jYXHvW5F5D_b8Vd_XCW6QjVYc44PqlTW33zP8x6LmlpDW2SFldK2ZHrKtW7jr-8v4rQ98CW20SBC793cwZzW7QyqZC8jSs2sW98WyjM8_zKwfW3C72f54dl20FVn7Z1s2fVxqWVwMWx18J_y92W72ZdqD7HjzYdW3bqG87438T4gW6-2gdy9fJjTRW8yNw3d6HwvJFV3VwX726fnPVW54Lr1h5Vdln0N5x6bTnjbW82W5C7xnT67B_dCW2zCN7Z65xynsW6vx10g2Hg12kW9dGxQK6V-t3VW5RjcSZ9ggkmRV1TtWD2BM_79W2Q7nTh3PLRhXW7Zv5Jb5vwh1GW1TzRhX5QgpgWW1xqsm48bZ3JzW3bbj_p94n57TVJLZww2tRy8M3hXQ1 )

We look forward to seeing you at both these sessions.

Regards,

Your HiveMQ Marketing Team

HiveMQ GmbH, Ergoldinger Straße 2a, Landshut, Germany

Manage preferences (https://hs-5867930.s.hubspotemail.net/hs/manage-preferences/unsubscribe?languagePreference=en&amp%3Bd=VnzSxg5pR2lTW2p76LK3-1rCSW45Qvcz1Zw56kW43QhSG3LFJ_1W4mKcrk4hN6NGW400xxl3KbsvFW3R0gy13z9Fz3W3yVRfB45RlhdW3P28X24hCPvhW43T2PJ8-zKhjW15gBJz878JrhW6PDWrL4WpGp2W5tgs2h8mK1fJVW-VLr630tr4MXk_7Qbw01gW3lFH573CPkQ0W7kbZxx1RcM-J3gLP2&amp%3Bv=3&_hsenc=p2ANqtz-_viSfGI4uCmy7e2NSG1IPkgV5nr2esYx-nEnrlWOaimcWMYa-9leRva86u-j7MBdAjmjP5svmey3BrZWBo3hcy2HdzHcTYypTfiic-ZKWntz5EdeEWD01MN803TD-5NFa2l2FikvvPyzS3xVzDw95DvVworg&_hsmi=156959882 )

You are receiving this email because you filled out a form on our website

or visited us at our booth at a tradeshow.

Twitter (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVqq5p1dzhGxW5r2R8b4QC9-yW861hN74xc2j1N7Hm8y73pl3rV1-WJV7CgZymW1gVq-f31kt0TW8D3_rP6_td5pW4SR_pP6ZppxkW3fG0PZ5dxtFGV8hy5680BDFFW770jkq1-11nLW93sxwD3VnMhdV5FrpV7KFdKRW99XKvq2hwzX4W1tng5G1Tfj7nW5kqlgm41DvpqVH-qgv16b82RW6Jqch_2z6HN6VYMfJh3Gt5FCW25w1S37x2jc1W1gdPJZ5bC9nyW2nLWld8FbDQBVdDsl-5JbjRZVmQ-B-4D2dqWW597Ky132CPmSW62_LJB2rYDSbW9l8Ynd28Zr2ZVp0Sbv5QyvncW27w0ph3Whn45W1M6ZyX5JJXlGW47Q9JP4Q195NN26d5wlmFTCkW5XN9DV6tlZtg3lRQ1 )

LinkedIn (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVqq5p1dzhGxW5r2R8b4QC9-yW861hN74xc2j1N7Hm8yr3pl3LV1-WJV7CgGTqW50KbsG60tPwKW3vM7sY3xXJnrN64608J8W4rNW71mKkh5hG6h-W2Qjl_l1XCJyMVyLcW21pB2D7W3Fm0q89dPL7hN1zDrKKLv1c9W8v2wyf1D5dStW7GK62G41PV0kW2cPY2D2vhcvMW17LNrV6VxQ2PW1PkkbV75V0hgW3bnyKZ2pPKYpW2r93mC6Dm20gW18R-FP37j2fSW1vMn-p4TyTQ3W3rzhZ569f60-VRn_p42wg-smW78vpZd5NFjttW48VsrT7DwMYWVLRS071cQ-c5VghcpB4JW2ZCW46_nw-2yLFNVW8-KMBC9jcj-GW60ZHVs57723jW8V-30J1mLzYmW3D92bm8n2lfkW2T2hLn6j1yLLW3HkYxb5BJTgD364b1 )

Facebook (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVqq5p1dzhGxW5r2R8b4QC9-yW861hN74xc2j1N7Hm8y73pl3rV1-WJV7CgFkLW38cWF231FPzMMf5XwmYyQpGV1M_0S7VnzMvW2YNG2z137SFPW3Qw0QX2_CR2KW8mQyfc2lHm0tW92NTyH5jX5rGW8Kw4299lQFbTW2DWc5J1Qjw-jW7gWq3V6BNNn0W7FlF7Q5v4N14N2LZ-dTYljsTN2Z1Lqvs1R10M6Z476V06kDW53nsZg8-nKbWW23d-Hv86ZQ7mW1vG0DM39_6XpW5kM_HH1P_6k3W6_-4mw7LN4CZW1-f7BC5v3-cMW51zwlC7lt-dDW4jmgxL4cpmtrW2Qtqnd821TlLW5Pf2_T3HD6r_W2kCdtH5lqK43N5dHW75CpY2CW96k0h51SNbRJVkd1fy1LnvG73bfQ1 )

YouTube (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVqq5p1dzhGxW5r2R8b4QC9-yW861hN74xc2j1N7Hm8wm5mVxSV3Zsc37CgClnVNbzBY145YFGW1swHxw72zTQ4W7XR7b46R8WzMW3GYgBj90sjG0W8F5jYx9dbfKSN3jRdN9pX6mCW6y0ppH6RLgsgW8T_M302vWt9KW6487Sf41VJXcW61Gg927t6jjyW5_4RBH39qhNYN4Y5CK8_DXJWW85LHBw2x7JZwW5DhXjp2bjCFHW9jqMX52LDN-GW19MKBK7kRWGgW743Xyv5Lt7wcW69C9jN73S9D3W5Y95FC7876GnW8wbrKB5byXdvW13Ytm-2l8-p4W36D4jn2sgBxmW5G8_jk6HZQsmW30c9S65CxG0RV-qndm2dWlSjW1sqskh4fdnK7W7m5Lzr1jgjd1W2bMqz04FBpXWW3zKLqP8_NKBNN49plPy7NnmzW7YX0HQ24sdg4N2cYl4kQyyG5377g1 )

**Comment by FibreFoX** [comment]
While debugging it seems to me, that the warning is a false-positive, because the way the passed value gets checked against `null`.

**Comment by HiveMQSupport** [comment]
Tune in to our special edition webinar to get first-hand information on the upcoming 4.7 release.

Last chance to register for our special edition webinar on

Wednesday, 15. Sept. 2021 at 5 PM CEST/ 11 AM ET / 8 AM PT

Reserve Your Spot Now
(https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWdJMY2dNkhyW8D3-5Q3-wm67W20x2Jc4xrVvYN5LPbRS5mVy7V3Zsc37CgDw6W3M4BwH6XdsQvW16yvYK5V9QT9W2v35xB5qKT1tW66J_n8982T46W70NxzZ17bJ_tN8RGc2Nj4WPYW8zfw6s8qmQfBMNVxNR3XRcGW71YF1G9jD3BvW4V5DlF1-mpXSW5TRTWP6VWdqtW3s4h_F8CyjpTW3zNpb65Wfw8-W3vTDss4MWd4XN88Rnnjy7WwDW8kpHB91MVqbPW66P2ZQ2cP06lW5JmSLQ7XxxqXW5Q-BWl47W7qlVpG2p91p8KZ7W2QNpz04XB1T-W4L9C5N4q_RgXW2XDCy931zDKpW6Zv7XL7d67mwW2YT3ZY7dz8SkW4jQQkW4045KNW7xcVgP5mp3GXW32Pk2b18khQKW1Hdv8m8X0dVTW4LRHJd6QhlNqN54z1Y2j_BV_W5flLPP5sllKJW4RTYwS7KGvkSN3GyDDRsbhgr33DT1 )

Hi hivemq/hivemq-community-edition,

Checking in one last time before our webinar this Wednesday on 'What's New in HiveMQ: Inside the Upcoming HiveMQ 4.7 Release.'

Why You Should Attend:

HiveMQ 4.7 will be released soon. In this webinar, Dominik Obermaier, CTO and co-founder of HiveMQ, and Georg Held, Engineering Manager at HiveMQ, will showcase the new features of HiveMQ 4.7 and discuss how you can benefit from upgrading to the new release.

Some of the highlights of HiveMQ 4.7 include:

- Easier operations for cloud-native deployments

- Exciting new Enterprise Security features

- Next level upgrades to HiveMQ Swarm – the MQTT load testing tool

Register Now
(https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWdJMY2dNkhyW8D3-5Q3-wm67W20x2Jc4xrVvYN5LPbRS5mVy7V3Zsc37CgP1YW4wqpPQ5YXqv8W3FsZH86cWshpW3v3Ln81xFz2bW1LQRZt8wP9jkVlvShk8Zl5-fW499Y8H3yGpPtN1vS8ZpzBjNKW1llnSb759v-KW2lFPN94P1kdLN5BfrBKswvQzW1P6rqk65ct3kW1r1WJf2l-8dMW1mXhj51GbHTmW5ZPln24cQbX4N5kVQxssfmJWW944Lbg5Pp-CJW2wHBsF7YTDMZW4RR-Td32_qRFW8zW2yg9jCMcrW1nfvXs47WbD0VpPlzp3Qc0ZmN4pW3pMppdV6W2Z1rm98tK9mMW8HZmqd3VtSkHW9cjqGZ2zzx-MVYWwSg3NLX_LW3X11282fxzYBW80PtW16lTBd5W31YK4M4f89rPW7LhL6n6-MTqmW2ZZPqH9j_8GXW21tJ2W9dtjlLV7YQ6P1NCfzrW6qgcp44WSYPc3h4q1 )

We look forward to seeing you at this interactive session.

Warm Regards,

The HiveMQ Team

HiveMQ GmbH, Ergoldinger Straße 2a, Landshut, Germany

Manage preferences (https://hs-5867930.s.hubspotemail.net/hs/manage-preferences/unsubscribe?languagePreference=en&amp%3Bd=VnzSxg5pR2lTW2p76LK3-1rCSW45Qvcz1ZtRX4W1Xv28f3_-rKDW3VxXjW45S3sJW4cKKr23KbsvFW3R0gy13z9Fz3W3yVRfB45RlhdW3P28X24hCPvhW43T2PJ8-zKhjW15gBJz6KynpJW7rVcxy6D7l4mW4-40w17hLJ8qVWzRPk5JhSlvMXk_7Qbv-8_W1Tp5gB2HsRRJW8_tdlM6XHj0Q2l-2&amp%3Bv=3&_hsenc=p2ANqtz-_R3cILdWPvqU-_1FBj5kYyGPbFnzFnURv7EEDyGdG4KdPF18oE6hUadJ_JfNjiH-eu3v-GhskmTF7WLfUIGjfIg7EgRjgjoGBFTS8SgUj9HG6pHvPZoA6dwFFZ9QrJuJJQhDmA479j8mZ10-FEX2r_hBtW6Q&_hsmi=159067984 )

You are receiving this email because you filled out a form on our website

or visited us at our booth at a tradeshow.

Twitter (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWdJMY2dNkhyW8D3-5Q3-wm67W20x2Jc4xrVvYN5LPbTk3pl3rV1-WJV7CgMlnW6WzSMk1xw7VJN3t5pGN5btbtW5WsNTR6yYssFW1JXQVM4vsmgrW1fPb9G3cdHp6W7fpZsD9gHbr2W88-Fyt6fRSyvW35Gxmm8ZS9dgW8ww9B-2ZZC98Mkc1xRPMxp2W14Cpwz2hR4bkW2nXxK_5NMv0rW39VBTl4hw6cPW87S3Mn7thrGXW8KDK305Bm_xYW2XvnQl24D6ryW4kx7323VFr9-W3PljqG1X0BbCW6xR5g_1NQgMcW5q6777332N6JVkWSdt4mS-VxW6bpZPv60NTRfW6c1j9K6g1WwLW80whhv3B4Sy8W57gPlY3mXx8VW1HFCbJ7X5GrlW7SyPyy93Kr5TN59vcJnHRqj13fxx1 )

LinkedIn (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWdJMY2dNkhyW8D3-5Q3-wm67W20x2Jc4xrVvYN5LPbTD3pl3LV1-WJV7CgB15W8N8tM43m-fycW4zd40P6P8h6jW2RS5qv3TLZzWW3MQd631qQwpsVTYNjq6_gvsbN6drBrDMlcZPW8gtRll3M7s-nW1vqX3t1W4rp7W1PdZXf8s-jMGW34yX3-2D63kfW7Nb-tW8Bm_sFW4k74Zj4KBXm5W73bBwd7pJv84W80fk8q2-cGTWW6RKGqW6Zt4cpW5fLXn91NSNN7N5jh0YQFNY7JW3-Gvx94Yl-Y9MzzFLc_v9yPW7ZRJl_7vVHY0W1RwLkV7yGTjcW6kggvJ87mnfZN5ZQyG7f5c6rW1GjF9S4dpPG3W7gHlNg7fvFRLW27P-3V3NzYDLW4fHGbg8q5fPDW4h5MTt6_w5JGW6D6sgN3k15M7W4jGNft83TsvJ3c8c1 )

Facebook (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWdJMY2dNkhyW8D3-5Q3-wm67W20x2Jc4xrVvYN5LPbTk3pl3rV1-WJV7CgYylN2d-TJ7XmNz0W4bXl5h6YJrHpW5qTbcD5BccHMW46TCpF4W4h3NVJqxD0508Y4BN5Dh00DlXDZWW99rQQ_4_w3dyW5s26bs4r8yVjW9jbMJp3pPM55W7CPNwW5FJCJ2W4gHYwT73J_JMW9hzD5T3YrKfmW22Dy0G7rt3Z_W3MCY8X5bd843W1r5trx1mtFZPW8N1Qdr6jFVFxW3y-LkH2Ph97vN4c4_YRKLPVlW91zcTC4zsMnpW7c1HrN1Vj1KVW2FcXH56SBDrZN7s74yt47GD2W1cPyQV5CRB90VTNY-l51mQJpW254KM82tyRK7VLXmt95bWbQZW8vHX7h19jKKgW6dkpKc7zvNxs34X91 )

YouTube (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWdJMY2dNkhyW8D3-5Q3-wm67W20x2Jc4xrVvYN5LPbRy5mVxSV3Zsc37CgC2dW1C7nQZ5GpXByW2K_l9V3kQqdlW76B9Gc5Z1Mj0W4gpcMw1XyD0QW4C7gzq6c0nRwW2vrcSB3bMm_KN5Sz7xKlXggSW87F0vJ43JQ0cW45JNpk1xVkwKVfBRNc6cs-rFW45WlgC4VBQb6W23xJRk2S-NxbW1K_fXP2z_V9fVqTByH1-JkR5W5lW3qc8FbPgrW7TBZ753qZBR_W7Jpxk48my7fqW8xMdHb4phNNdW3k0fPt78nTFJW527xX85GqDZLVq6Z5R1DtQ0-W5YJK2M99vcYkW8m-Snn7tMFNFVGSGDd2WLGw_W3MLKTH882CmtW3rj6n71PBy2FW6DMjvZ8qZGLTW4yMcYl8sCR32W8HZ2Bp4QJGc5Vqwg574P2WlrW3nC3zV1qWh8qVf94r72QCJMg3cJ01 )
